---
title: Final Dashboard
author: Sofia Charlot
output: github_document
---


# Dashboard Details

This dashboard serves as an interactive infographic for the masters thesis: Community Assets Rooted in Place: Associations Between Local Food Systems and Food Insecurity in Metro Atlanta by Sofia Charlot, MPH. It summarizes the thesis and allows users to explore the topic themselves.

This dashboard is a contribution towards better alignment across the communal and commercial components of the Metro Atlanta area local food system. It aims to uncover findings that lead to better alignment across components, strategic investments into food outlets, better food security upstream, and better health outcomes downstream.

## Accessing the Dashboard

View the dashboard using this link to the Github page: https://s-charlo.github.io/thesis_dashboard/

# Project Directory Contents

- The source code is included in the `index.Rmd` file.

- The analytic dataset is not included in this repository.

- The raw_data folder contains .rds files with the raw data for dashboard tables 

- The image folder contains photos included in the dashboard

- The rosm.cache folder includes cartolight images for map generation

- the tl_2020_13_all folder contains the TIGER/Line shapefiles for map generation




    






